"""
Django settings for Vimto project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

VIMTO_DEBUG = True
DEBUGDATAFILES = False

#########################################################################
# VIMTO Folders and Files settings
VIMTO_FILE_ROOT = "/var/www/MediaRoot/Vimto"
VIMTO_FILE_RAW = "/var/www/MediaRoot/Vimto/Raw"
VIMTO_FILE_EDITED_ROOT = "/var/www/MediaRoot/Vimto/Edited"
VIMTO_FILE_CONFIGDATA = "/var/www/MediaRoot/Vimto/ConfigData"

VIMTO_FILE_EXCLUSIONLIST = "/var/www/MediaRoot/Vimto/Excluded.xml"


#########################################################################
# Celery settings
CELERY_BROKER_URL = 'amqp://guest:guest@localhost//'
CELERY_TASK_RESULT_EXPIRES = 18000  # 5 hours.
CELERY_RESULT_BACKEND = "database"
CELERY_RESULT_DBURI = "mysql://vimtouser:vimto1234@localhost/vimto_ws"
#: Only add pickle to this list if your broker is secured
#: from unwanted access (see userguide/security.html)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_IMPORTS = ('celeryproj.tasks',)
#########################################################################
BOOTSTRAPLEVELS = ["default", "primary", "success", "info", "warning", "danger"]

SENSORS = (
        ('PFL', 'Power Front Left'),
        ('PFR', 'Power Front Right'),
        ('PRL', 'Power Rear Left'),
        ('PRR', 'Power Rear Right'),
        ('TFL', 'Trail Front Left'),
        ('TFR', 'Trail Front Right'),
        ('TRL', 'Trail Rear Left'),
        ('TRR', 'Trail Rear Right'),
)

DIRECTIONS = (
         ('BW', 'Birmingham to Wolvehampton'),
         ('WB', 'Wolverhampton to Birmingham'),
         ('TD', 'TO the Depot'),
         ('FD', 'FROM the Depot'),
)



TRAM_CSV_DATA = {}
TRAM_CSV_HEADER = {}
TRAM_19 = {}
TRAM_CSV_DATA_CURR = []
XMLSensor = None
